baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Graeme West"
theme = "hugo-identity-theme"

[params]
    [params.personal]
    # If name is not set, author is used
    name = "Graeme West"
    # Avatars can be written to images/avatars/
    avatar = "profile-graeme-cropped.png"
    position = "Passionate about software"
    livesIn = "Glasgow, Scotland"
    scope = [
        "Tech writer and localisation expert",
        "Certified Scrum Master",
        "Co-founder of International FOSS Law Review (IFOSSLR)"
      ]
    biography = """Graeme West is a hoopy frood who really knows where his towel is."""

    [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "graeme@heliocentrik.net"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    enable = true
    title = "Contact"
    namePlaceholder = "Name"
    emailPlaceholder = "Email"
    messagePlaceholder = "Message"
    buttonText = "Send it"
    success = "Thank you for contacting me."
    error = "Sorry, but there was a problem submitting the contact form. Woopsie! Try contact me at: "

    # Google invisible captcha
    #[params.contact.captcha]
    #  sitekey = ""


    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    #  name = "someID"
    #  value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  # You may change these with your social links or add others

#   [[params.social]]
#     title = "Twitter"
#     icon = "fa-twitter"
#     link = "#"
#     target = "_blank"

  [[params.social]]
    title = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://www.linkedin.com/in/graemewest/"
    target = "_blank"

  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Graeme West"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

#   # Credits
#   [[params.credits]]
#     # Title is used as URL text
#     title = "HTML5UP"
#     # Text will be used to explain the credit
#     text = "Design by"
#     link = "https://html5up.net"